### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by filmkorn** [adrianpueyo/KnobScripter#2]
Hello Adrian,

First of all, fantastic tool - thanks for providing it!
If you don't mind, can you tag a release here on github, please? It would make versioning releases a tad easier in our system.

Cheers,

Mitja

**Comment by adrianpueyo** [comment]
Hi Mitja, Sorry for the >1-year-late response!! I got back to it, and I tagged yesterday's [v2.4 release](https://github.com/adrianpueyo/KnobScripter/releases/tag/v2.4).

Cheers!
