### ISSUE TITLE
[feature] Custom shortcut to clear output window

### ISSUE THREAD

**Issue by fynnay** [adrianpueyo/KnobScripter#3]
I absolutely **love** the panel and am currently starting to use it to replace the script editor!

I do miss the `Ctrl+Backspace` shortcut for clearing the output window a lot. It would be great to implement that or an option to set a custom shortcut. That way You wouldn't have to click the output window first every time.

**Comment by adrianpueyo** [comment]
Great idea! Feature added to 2.4. Will publish in the next days.
