### ISSUE TITLE
Nuke 13 Compatibility and more

### ISSUE THREAD

**Issue by sisoe24** [adrianpueyo/KnobScripter#8]
Hey! First of all thank you for the time you put into this tool! Recently I've been using it more and more and as a token of appreciation I would like to lend a hand if needed.

For starters, I have a working branch that adds compatibility to Python3/Nuke 13. The branch is made out of master because the develop branch seems to be very much still working in progress.

The update mostly fixed some Python2/3 compatibility and some unrelated random issues including #1. Some of the issues as far as I can tell (just skimming through the code because the develop build doesn't work) are still present in the develop branch, so it might give you an idea at what to look into. When the develop branch will be merged into master will override anything anyway so there are not going to be any conflicts, but at least for now there will be working version for Nuke 11, 12 and 13.

Would you want me to make a PR? or you don't want to change anything before the new update as it might be imminent? 

I also have some updates proposal that I would gladly assist or implement myself but we can discuss this later if appropriate.

Besides all this I teach privately Python to some Nuke artist so if I can help by doing code reviews or something else, let me know!

Cheers and thanks again for this tool.

**Comment by adrianpueyo** [comment]
Thanks a lot for this!! 2.5 years later... Sorry I missed it 😆
Hopefully all is resolved now. Closing the issue, but feel free to reopen if anything comes up.
